/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fastpng_Native_PNG_Writer */

#ifndef _Included_fastpng_Native_PNG_Writer
#define _Included_fastpng_Native_PNG_Writer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fastpng_Native_PNG_Writer
 * Method:    write8BitPNG
 * Signature: ([BII[B[B[BLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_fastpng_Native_1PNG_1Writer_write8BitPNG
  (JNIEnv *, jobject, jbyteArray, jint, jint, jbyteArray, jbyteArray, jbyteArray, jstring);

/*
 * Class:     fastpng_Native_PNG_Writer
 * Method:    writeFullColourPNG
 * Signature: ([IIILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_fastpng_Native_1PNG_1Writer_writeFullColourPNG
  (JNIEnv *, jobject, jintArray, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
