require 'testlib'

TestLib::startIJ
TestLib::waitForWindow("Fiji")
TestLib::clickMenuItem("Plugins>Fake Neuron")
TestLib::waitForWindow("New Fake-Neuron")
TestLib::clickButton("  OK  ")
TestLib::waitForWindow("Fake Neuron")
TestLib::waitForWindow("Fiji")
TestLib::clickMenuItem("Plugins>3D Viewer")
TestLib::waitForWindow("ImageJ 3D Viewer")
TestLib::waitForWindow("Add ...")
TestLib::clickButton("  OK  ")
sleep 5
TestLib::mousePress(1, "ImageJ 3D Viewer", 273, 347)
TestLib::mouseMove(0, -4)
TestLib::mouseMove(0, -5)
TestLib::mouseMove(0, -4)
TestLib::mouseMove(0, -6)
TestLib::mouseMove(0, -1)
TestLib::mouseMove(1, -3)
TestLib::mouseMove(0, -3)
TestLib::mouseMove(0, -3)
TestLib::mouseMove(0, -4)
TestLib::mouseMove(0, -4)
TestLib::mouseMove(0, -2)
TestLib::mouseMove(0, -6)
TestLib::mouseMove(0, -3)
TestLib::mouseMove(0, -3)
TestLib::mouseMove(1, -2)
TestLib::mouseMove(0, -2)
TestLib::mouseMove(0, -1)
TestLib::mouseMove(0, -1)
TestLib::mouseMove(1, -2)
TestLib::mouseMove(0, -3)
TestLib::mouseMove(0, -1)
TestLib::mouseMove(1, -1)
TestLib::mouseMove(0, -3)
TestLib::mouseMove(0, -1)
TestLib::mouseMove(0, -2)
TestLib::mouseMove(0, -1)
TestLib::mouseMove(0, -1)
TestLib::mouseMove(0, -5)
TestLib::mouseMove(0, -2)
TestLib::mouseMove(0, -5)
TestLib::mouseMove(0, -2)
TestLib::mouseMove(-1, -2)
TestLib::mouseMove(0, -4)
TestLib::mouseMove(0, -2)
TestLib::mouseMove(-1, -5)
TestLib::mouseMove(-1, -2)
TestLib::mouseMove(-1, -6)
TestLib::mouseMove(0, -2)
TestLib::mouseMove(-1, -6)
TestLib::mouseMove(-1, -2)
TestLib::mouseMove(0, -3)
TestLib::mouseMove(-1, -2)
TestLib::mouseMove(0, -3)
TestLib::mouseMove(-1, -2)
TestLib::mouseMove(-1, -4)
TestLib::mouseMove(0, -1)
TestLib::mouseMove(0, -1)
TestLib::mouseMove(0, -1)
TestLib::mouseMove(0, -1)
TestLib::mouseMove(0, -1)
TestLib::mouseRelease(1)
