#!/bin/sh

set -e

export JAVA_HOME=@@INSTALLED_JVM_ROOT@@
export LD_LIBRARY_PATH=@@LD_LIBRARY_PATH@@:$(cat /usr/lib/fiji/jni/*.conf 2> /dev/null | tr '\n' ':')

/usr/lib/fiji/fiji --class-path @@JAVA_3D_JARS@@:/usr/share/java/jama.jar:/usr/share/java/bsh.jar:/usr/share/java/batik-all.jar:/usr/share/java/xml-apis-ext.jar --fiji-dir /usr/lib/fiji/ "$@"
