#!/bin/sh

set -e

export JAVA_HOME=@@INSTALLED_JVM_ROOT@@
export LD_LIBRARY_PATH=@@LD_LIBRARY_PATH@@:$(cat /usr/lib/fiji/jni/*.conf|tr '\n' ':')

/usr/lib/fiji/fiji --class-path @@JAVA_3D_JARS@@ --fiji-dir /usr/lib/fiji/ "$@"
