/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fastjpeg_Native_JPEG_Writer */

#ifndef _Included_fastjpeg_Native_JPEG_Writer
#define _Included_fastjpeg_Native_JPEG_Writer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fastjpeg_Native_JPEG_Writer
 * Method:    writeFullColourJPEG
 * Signature: ([IIILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_fastjpeg_Native_1JPEG_1Writer_writeFullColourJPEG
  (JNIEnv *, jobject, jintArray, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
